# fake-talos-serviceaccount-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceaccounts.talos.dev
spec:
  group: talos.dev
  scope: Namespaced
  names:
    plural: serviceaccounts
    singular: serviceaccount
    kind: ServiceAccount
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
