apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifest/

images:
  - name: ghcr.io/procinger/tuppr-dashboard/tuppr
    newName: localhost:5001/tupper-dashboard/dashboard
