apiVersion: v1
kind: Secret
metadata:
  name: tuppr-talosconfig
  namespace: default
type: Opaque
stringData:
  config: |
    context: default
    contexts:
      default:
        endpoints:
          - https://10.0.0.1:50000
        ca: ""
        crt: ""
        key: ""
