k8s_yaml('talos-serviceaccount-crd.yaml')
k8s_resource(
  new_name = 'serviceaccounts.talos.dev',
  objects = [
    'serviceaccounts.talos.dev:CustomResourceDefinition:default',
  ]
)

k8s_yaml('talosconfig.yaml')
k8s_resource(
  new_name = 'talosconfig',
  objects = [
    'tuppr-talosconfig:Secret:default'
  ],
)

# renovate: datasource=github-releases depName=home-operations/tuppr
TUPPR_VERSION = '0.2.4'

load('ext://helm_resource', 'helm_repo', 'helm_resource')
helm_resource('tuppr',
  'oci://ghcr.io/home-operations/charts/tuppr',
  namespace = 'default',
  flags = [
    '--create-namespace',
   '--version=' + TUPPR_VERSION,
  ],
  resource_deps = [
    'serviceaccounts.talos.dev',
    'talosconfig'
  ]
)

local_resource(
  'tuppr-upgrade',
  cmd='''
set -eu

for i in $(seq 1 30); do
  if kubectl apply -f tuppr-upgrade.yaml; then
    exit 0
  fi

  echo "tuppr webhook not ready yet, retrying..."
  sleep 2
done

exit 1
''',
  deps=['tuppr-upgrade.yaml'],
  resource_deps=['tuppr'],
)

k8s_yaml(kustomize('./'))
k8s_resource(
  workload = 'tuppr-dashboard',
  labels = ['Dashboard'],
  port_forwards = ['8080:8080'],
  resource_deps = [
    'tuppr-upgrade',
    'tuppr',
  ]
)
