apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuppr-dashboard
  namespace: system-upgrade
  labels:
    app.kubernetes.io/name: tuppr-dashboard
    app.kubernetes.io/instance: tuppr-dashboard
    app.kubernetes.io/version: "v0.0.9"
    app.kubernetes.io/managed-by: Kustomize
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tuppr-dashboard
      app.kubernetes.io/instance: tuppr-dashboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tuppr-dashboard
        app.kubernetes.io/instance: tuppr-dashboard
    spec:
      serviceAccountName: tuppr-dashboard
      containers:
        - name: dashboard
          image: ghcr.io/procinger/tuppr-dashboard/dashboard:v0.0.9
          ports:
            - containerPort: 8080
              name: dashboard
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 65532
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: dashboard
            periodSeconds: 15
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: dashboard
            periodSeconds: 15
