apiVersion: v1
kind: ServiceAccount
metadata:
  name: tuppr-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuppr-dashboard
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["tuppr.home-operations.com"]
    resources: ["kubernetesupgrades", "talosupgrades"]
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tuppr-dashboard
subjects:
  - kind: ServiceAccount
    name: tuppr-dashboard
    namespace: default
roleRef:
  kind: ClusterRole
  name: tuppr-dashboard
  apiGroup: rbac.authorization.k8s.io
