name: Run CI Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  test:
    name: Run CI Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install K8S tooling
        uses: yokawasa/action-setup-kube-tools@v0.13.1
        with:
          setup-tools: |
            kubectl
            kustomize
            helm
            tilt
          kubectl: '1.36.1'
          kustomize: '5.8.1'
          helm: '4.1.3'
          tilt: '0.37.3'

      - name: Create KinD Cluster
        run: ${{ github.workspace }}/local-dev/kind-with-registry.sh

      - name: Run Tilt CI
        run: tilt ci

      - name: Start port-forward
        run: |
          kubectl port-forward \
            deployment/tuppr-dashboard \
            8080:8080 \
            -n default \
            > portforward.log 2>&1 &

          echo $! > portforward.pid

      - name: Wait for port-forward
        run: |
          for i in $(seq 1 30); do
            if nc -z 127.0.0.1 8080; then
              echo "port-forward ready"
              exit 0
            fi

            sleep 2
          done

          echo "port-forward failed"
          cat portforward.log
          exit 1

      - name: Run curl tests
        run: |
          curl -v http://127.0.0.1:8080/nodes | jq
          curl -v http://127.0.0.1:8080/tuppr/talos | jq
          curl -v http://127.0.0.1:8080/tuppr/kubernetes | jq
          

      - name: Export KinD logs
        run: kind export logs ${{ github.workspace }}/kind-logs

      - name: Upload KinD logs
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: kind
          path: '${{ github.workspace }}/kind-logs'
          retention-days: 3
